# This workflow runs the JSON checker on each vendordep JSON file.

name: Bazel CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-json-checker"
  run-json-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history so we can use git diff

    - name: Maybe setup BuildBuddy key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      if: ${{ env.API_KEY != '' }}
      shell: bash
      run: |
          echo "API Key detected!"
          echo "build:build_buddy --remote_header=x-buildbuddy-api-key=${{ env.API_KEY }}" > .buildbuddy-auth.rc

    - name: Run check
      run: |
        bazel test //... -k --config=ci
