name: Generate Bundle

on:
  push:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python generate_year_bundle.py -y 2024 outputs
      - run: python generate_year_bundle.py -y 2025 outputs
      - uses: actions/upload-artifact@v4
        with:
          name: repository
          path: outputs
      # eventually upload to artifactory
